name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependency
      run: sudo apt update && sudo apt install -yq build-essential cmake ragel git libboost-all-dev
    - name: abseil-cpp
      run: git clone https://github.com/abseil/abseil-cpp repo && cd repo && mkdir -p bin && cd bin && cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && cmake --build . && sudo cmake --install .
    - name: make
      run: make
    - name: make check
      run: make check
